version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: perf-bench-postgres
    environment:
      POSTGRES_USER: perfbench
      POSTGRES_PASSWORD: perfbench_password
      POSTGRES_DB: perf_bench_suite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perfbench"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: perf-bench-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perf-bench-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://perfbench:perfbench_password@postgres:5432/perf_bench_suite
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
